### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by olgunkaya** [halilozel1903/Covid19Stats#1]
I wouldn't call an interface file name as ...Interface. It is already interface and pretty obvious. 
So for the api folder. I would recommend you some renaming refactor operations. 

1. As per retrofit namings and their documentation in [here](https://square.github.io/retrofit/) 
`public interface GitHubService {
  @GET("users/{user}/repos")
  Call<List<Repo>> listRepos(@Path("user") String user);
}`
Rename your ApiInterface.java to CountryService.java

2. The class APIClient could be RetrofitBuilder to build retrofit instance for a given base_url. Or even no need for it. Retrofit is already providing a one liner builder pattern to get you an instance.

**Comment by halilozel1903** [comment]
Sorry for the delay. 

I updated the names of the classes.

I didn't fully understand the second item.

Thanks for feedbacks

**Comment by olgunkaya** [comment]
Sorry for the delay. So since you are already generating only a retrofit instance in the CoronaApi class. I believe that's not a requirement to hold it. But still you can apply the factory pattern for that manner and use the name CoronaApiClientFactory
with a method named getApiClient

**Comment by halilozel1903** [comment]
I see. Thanks
